### ISSUE TITLE
Borrar el registro de un paciente

### ISSUE THREAD

**Issue by gonzalo991** [CodeSystem2022/ProyectoIntegrador-TercerSemestre-LosChiperos#10]
Definir una función para borrar un paciente:
    - En su rama crear el archivo api.py
    - Definir la función borrar_paciente
    - Realizar la llamada a la base de datos para borrar el registro
    - Manejar Excepciones

**Comment by Leonardo-Valdez** [comment]
enviamos al repositorio funcion borrar paciente
