### ISSUE TITLE
Agregar Integrante al equipo

### ISSUE THREAD

**Issue by gonzalo991** [CodeSystem2022/ProyectoIntegrador-TercerSemestre-LosChiperos#12]
Definir una funcion para agregar un integrante del equipo al registro en la base de datos:
   - En su rama crear el archivo data.py
   - Definir la funcion agregar_integrante
   - Declarar las variables que se recibiran del formulario, las variables son:
       1. nombre
       2. apellido
       3. role
       4. description
       5. imgUrl
       6. twitter
       7. linkedin
       8. github
   - Realizar el llamado a la base de datos para agregar el registro
   - Manejar Excepciones

**Comment by catastones** [comment]
se renombra data.py a teamController . Funcion agregar_member //funcion  listar_team

>
