### ISSUE TITLE
Declarar las rutas

### ISSUE THREAD

**Issue by gonzalo991** [CodeSystem2022/ProyectoIntegrador-TercerSemestre-LosChiperos#14]
Declarar las rutas e importar funciones:
     - En el archivo app.py creado en su rama importar las funciones:
        1. home
        2. agregar_paciente
        3. editar_paciente
        4. borrar_paciente
        5. listar_equipo
        6. agregar_integrante
        7. login
     - Declarar las rutas correspondientes a cada funcion

**Comment by NicolasZelarayan** [comment]
definimos las rutas en el archivo app.py ademas se agrega docker y archivos con requirements
