### ISSUE TITLE
Vista de entrada para el personal

### ISSUE THREAD

**Issue by gonzalo991** [CodeSystem2022/ProyectoIntegrador-TercerSemestre-LosChiperos#16]
Creamos la vista que se mostrará al ingresar a la plataforma:
       - Hacer un pull de la rama main
       - Crear una nueva rama con su nombre + la palabra frontend
       - En el archivo index2.html crear la vista que se mostrará al personal una vez hayan ingresado a la plataforma
       - Hacer un push con los cambios a la rama correspondiente (rama con su nombre + la palabra frontend)

**Comment by Agustin-Gomez-a** [comment]
se agrega vista para usuarios logueados
