### ISSUE TITLE
Vista del Equipo

### ISSUE THREAD

**Issue by gonzalo991** [CodeSystem2022/ProyectoIntegrador-TercerSemestre-LosChiperos#21]
Creamos la vista donde se mostrarán los integrantes del equipo:
- Hacer un pull de la rama main
- Crear una nueva rama con su nombre + la palabra frontend
- En el archivo team.html crear la vista para mostrar los integrantes del equipo
- Hacer un push con los cambios a la rama correspondiente (rama con su nombre + la palabra frontend)

**Comment by catastones** [comment]
Html creado con exito
