### ISSUE TITLE
Scrips modal

### ISSUE THREAD

**Issue by gonzalo991** [CodeSystem2022/ProyectoIntegrador-TercerSemestre-LosChiperos#24]
En la carpeta templates, dentro de la carpeta javascript:
- En el archivo modalFormNewMember.js escribir las funciones necesarias para agregar un nuevo miembro al equipo
- Enviar los cambios a su rama frontend

**Comment by NicolasZelarayan** [comment]
subimos codigo para abrir modal para insertar nuevos miembros
