### ISSUE TITLE
Configuración del servidor

### ISSUE THREAD

**Issue by gonzalo991** [CodeSystem2022/ProyectoIntegrador-TercerSemestre-LosChiperos#3]
- Crear el archivo app.py
- Configurar el servidor
- Crear la carpeta templates y configurar el servidor para que la reconozca

**Comment by NicolasZelarayan** [comment]
se crea archivo app.py

**Comment by NicolasZelarayan** [comment]
levantamos una instancia en azure para realizar despliegue de aplicacion

**Comment by NicolasZelarayan** [comment]
se configura instancia, pero por falta de permisos se aguarda la aprobacion del owner dela organizacion. mientras tanto se configura desde otro repositorio privado el servidor, una vez aprobado se cambiara la rama del repositorio

**Comment by gonzalo991** [comment]
Tarea finalizada!
